name: models
description: "Nextone models"
version: 0.0.1

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  auto_mappr_annotation: ^2.2.0
  firebase_auth: ^5.6.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  auto_mappr: ^2.5.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

