name: nextone
description: "NextOne app"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/logos/android_playstore.png"
  image_path: "assets/logos/android_playstore.png"
  image_path_ios: "assets/logos/ios_appstore.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
