name: nextone
description: "NextOne app"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+12

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  auto_route: ^9.3.0+1
  flutter_svg: ^2.1.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  flutter_hooks: ^0.21.2
  flutter_bloc: ^9.1.1
  nextone_core:
    path: packages/nextone_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13

flutter_launcher_icons:
  image_path_android: "assets/logos/android_icon.png"
  image_path_ios: "assets/logos/ios_icon.png"
  adaptive_icon_background: "#FF3B30"
  adaptive_icon_foreground: "assets/logos/android_icon.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  background_image: "assets/images/stage_background.png"
  image_ios: "assets/logos/ios_icon.png"
  image_android: "assets/logos/ios_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
