// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH6UIRdDmU-iL2I12tHmIT96RFrmsoy_g',
    appId: '1:133402782975:android:49ffeb814a32e4605eb0ca',
    messagingSenderId: '133402782975',
    projectId: 'nextone-af5e6',
    storageBucket: 'nextone-af5e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzCAna363jDLjG54z3ltpVf_Pts0UUVK8',
    appId: '1:133402782975:ios:45b878770c7be4545eb0ca',
    messagingSenderId: '133402782975',
    projectId: 'nextone-af5e6',
    storageBucket: 'nextone-af5e6.firebasestorage.app',
    iosBundleId: 'com.silvanosolutions.nextone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzCAna363jDLjG54z3ltpVf_Pts0UUVK8',
    appId: '1:133402782975:ios:b81cf9cb93babac35eb0ca',
    messagingSenderId: '133402782975',
    projectId: 'nextone-af5e6',
    storageBucket: 'nextone-af5e6.firebasestorage.app',
    iosBundleId: 'com.example.nextone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpYqL3TIdJs3HsdFrTwfadLip0a21OrEY',
    appId: '1:133402782975:web:42b7d30aae4ac1e55eb0ca',
    messagingSenderId: '133402782975',
    projectId: 'nextone-af5e6',
    authDomain: 'nextone-af5e6.firebaseapp.com',
    storageBucket: 'nextone-af5e6.firebasestorage.app',
    measurementId: 'G-BYFY6DYY36',
  );
}
