name: nextone_core
description: "NextOne backend."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  cloud_firestore: ^5.6.9
  models:
    path: ../models
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator:
  build_runner:
  freezed: ^2.5.2
  json_serializable: ^6.8.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

