name: Distribution Workflow

on:
  pull_request:
    branches: ["develop"]
    types: 
      - closed

jobs:
  build-app:
    if: github.event.pull_request.merged == true
    runs-on: macos-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.24.3

      - name: Install dependencies
        run: |
          flutter pub get
      
      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > android/app/google-services.json

      - name: Decode and create GoogleService-Info.plist
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Build APK
        run: flutter build apk --debug 

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: upload artifact to Firebase App Distribution
        uses: emertozd/Firebase-Distribution-Github-Action@v2
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_APP_DISTRIBUTION_CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: build/app/outputs/flutter-apk/app-debug.apk

      - name: Set up CocoaPods
        run: |
          cd ios
          pod install
          cd ..
      
      - name: Build iOS IPA
        run: |
          flutter build ios --debug --no-codesign

      - name: Distribute IOS via Firebase
        uses: emertozd/Firebase-Distribution-Github-Action@v2
        with:
          appId: ${{secrets.FIREBASE_IOS_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_APP_DISTRIBUTION_CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: build/ios/ipa/*.ipa